-- ЧИСТКА
DROP TABLE IF EXISTS compilation_events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;

DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS requests CASCADE;

-- ПОЛЬЗОВАТЕЛИ
CREATE TABLE IF NOT EXISTS users (
id BIGSERIAL PRIMARY KEY,
name  VARCHAR(250) NOT NULL,
email VARCHAR(254) NOT NULL UNIQUE
);

-- КАТЕГОРИИ
CREATE TABLE IF NOT EXISTS categories (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL UNIQUE
);

-- СОБЫТИЯ
CREATE TABLE IF NOT EXISTS events (
id BIGSERIAL PRIMARY KEY,
annotation VARCHAR(2000) NOT NULL,
description VARCHAR(7000) NOT NULL,
title VARCHAR(120) NOT NULL,
category_id  BIGINT NOT NULL REFERENCES categories(id),
initiator_id BIGINT NOT NULL REFERENCES users(id),
event_date   TIMESTAMP NOT NULL,
created_on   TIMESTAMP NOT NULL DEFAULT now(),
published_on TIMESTAMP NULL,
paid BOOLEAN NOT NULL DEFAULT FALSE,
participant_limit   INT NOT NULL DEFAULT 0,
request_moderation  BOOLEAN NOT NULL DEFAULT TRUE,
state VARCHAR(16) NOT NULL CHECK (state IN ('PENDING','PUBLISHED','CANCELED')),
location_lat DOUBLE PRECISION NOT NULL,
location_lon DOUBLE PRECISION NOT NULL
);

-- ЗАЯВКИ НА УЧАСТИЕ
CREATE TABLE IF NOT EXISTS requests (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
event_id BIGINT REFERENCES events(id),
requester_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
status VARCHAR(9) NOT NULL,
CONSTRAINT pk_request PRIMARY KEY (id)
);

-- ПОДБОРКИ (compilations)
CREATE TABLE IF NOT EXISTS compilations (
id      BIGSERIAL PRIMARY KEY,
pinned  BOOLEAN NOT NULL DEFAULT FALSE,
title   VARCHAR(50) NOT NULL UNIQUE
);

-- Связь "подборка -> события" как @ElementCollection(Set<Long>)
CREATE TABLE IF NOT EXISTS compilation_events (
compilation_id BIGINT NOT NULL,
event_id       BIGINT NOT NULL,
PRIMARY KEY (compilation_id, event_id),
FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
FOREIGN KEY (event_id)       REFERENCES events(id)       ON DELETE CASCADE
);

-- ИНДЕКСЫ
CREATE INDEX IF NOT EXISTS ix_events_event_date ON events(event_date);
CREATE INDEX IF NOT EXISTS ix_events_state      ON events(state);
CREATE INDEX IF NOT EXISTS ix_events_category   ON events(category_id);
CREATE INDEX IF NOT EXISTS ix_events_paid       ON events(paid);

CREATE INDEX IF NOT EXISTS ix_compilations_pinned ON compilations(pinned);
CREATE INDEX IF NOT EXISTS ix_compilation_events_event ON compilation_events(event_id);
